name: Update Podspec and Create Tag

on:
  push:
    branches:
      - main  # Виконувати лише для комітів у master

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Потрібно для коректної генерації версії

      - name: Generate next version
        id: version
        uses: conventional-actions/next-version@v1

      - name: Get podspec file
        id: podspec
        run: echo "podspec_file=$(ls *.podspec)" >> $GITHUB_ENV

      - name: Update podspec version
        run: |
          sed -i'' -E "s/(s.version[[:space:]]*=[[:space:]]*[\"'])([0-9]+\.[0-9]+\.[0-9]+)([\"'])/\1${{ steps.version.outputs.version }}\3/" ${{ env.podspec_file }}
          echo "Updated podspec to version ${{ steps.version.outputs.version }}"

      - name: Commit updated Podspec
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.podspec_file }}
          git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          git push

      - name: Create and push new tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
