name: Update Podspec and Create Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: version
        uses: conventional-actions/next-version@v1
        
      - name: Remove 'v' prefix from version
        run: |
          echo "CLEAN_VERSION=${VERSION#v}" >> $GITHUB_ENV
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Get podspec file
        id: podspec
        run: echo "podspec_file=$(ls *.podspec)" >> $GITHUB_ENV

      - name: Update podspec version
        run: |
          sed -i'' -E "s/(s.version[[:space:]]*=[[:space:]]*[\"'])([0-9]+\.[0-9]+\.[0-9]+)([\"'])/\1${{ env.CLEAN_VERSION }}\3/" ${{ env.podspec_file }}
          echo "Updated podspec to version ${{ env.CLEAN_VERSION }}"

      - name: Commit updated Podspec
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ${{ env.podspec_file }}
          git commit -m "Bump version to ${{ env.CLEAN_VERSION }}"
          git push

      - name: Create and push new tag
        run: |
          git tag ${{ env.CLEAN_VERSION }}
          git push origin ${{ env.CLEAN_VERSION }}
