name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate next version
        id: version
        uses: conventional-actions/next-version@v1
        with:
          prefix: ""
          tag-prefix: ""

      - name: Update podspec version
        run: |
          sed -i'' -E "s/(s.version[[:space:]]*=[[:space:]]*[\"'])([0-9]+\.[0-9]+\.[0-9]+)([\"'])/\1${{ steps.version.outputs.version }}\3/" *.podspec
          echo "Updated podspec to version ${{ steps.version.outputs.version }}"

      - name: Commit updated podspec
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.podspec
          git commit -m "Bump version to ${{ steps.version.outputs.version }}"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: "### Changes in this release:\n- Auto-generated release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
